[package]
name = "nordic2017"
version = "0.1.0"
authors = ["lislis <mail@lislis.de>"]

[[bin]]
name = "get-balsamic-vinegar"
path = "src/main.rs"

[dependencies]
piston_window = "0.64.0"
find_folder = "0.3.0"
rand = "0.3.14"
piston2d-sprite = "0.35.0"
piston-ai_behavior = "0.19.0"
